import { StyleSheet, Platform } from 'react-native';
import { COLORS, TOP_INSET } from './theme';

export const styles = StyleSheet.create({
  authContainer: { flex: 1, justifyContent: 'center', padding: 25, backgroundColor: 'transparent' },
  title: { fontSize: 36, fontWeight: '900', textAlign: 'center', color: COLORS.textPrimary, marginBottom: 8, letterSpacing: -0.5 },
  subtitle: { fontSize: 18, color: COLORS.textSecondary, textAlign: 'center', marginBottom: 40, fontWeight: '500' },
  choiceButton: { backgroundColor: COLORS.tabBar, padding: 22, borderRadius: 24, marginBottom: 20, shadowColor: COLORS.tabBar, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8 },
  buttonText: { color: '#fff', fontSize: 18, fontWeight: 'bold', textAlign: 'center', letterSpacing: 0.5 },
  subText: { color: 'rgba(255,255,255,0.8)', fontSize: 13, textAlign: 'center', marginTop: 4 },
  input: { backgroundColor: COLORS.card, borderRadius: 16, padding: 18, fontSize: 16, marginBottom: 15, color: COLORS.textPrimary, width: '100%', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  inputError: { borderWidth: 1.5, borderColor: COLORS.error },
  errorText: { color: COLORS.error, fontSize: 14, marginBottom: 15, alignSelf: 'flex-start', marginTop: -10, marginLeft: 5 },
  button: { backgroundColor: COLORS.tabBar, padding: 20, borderRadius: 16, alignItems: 'center', width: '100%', shadowColor: COLORS.tabBar, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 6 },
  backButton: { marginTop: 30, alignSelf: 'center', padding: 15 },
  backButtonText: { color: COLORS.textSecondary, fontSize: 16, fontWeight: '600' },
  linkText: { color: COLORS.textSecondary, textAlign: 'center', fontSize: 16, fontWeight: '700' },
  wizardOptionBtn: { backgroundColor: COLORS.card, padding: 24, borderRadius: 24, marginBottom: 15, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  wizardOptionText: { fontSize: 20, fontWeight: 'bold', color: COLORS.textPrimary },
  wizardSquareBtn: { backgroundColor: COLORS.card, width: '31%', aspectRatio: 1, borderRadius: 24, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  wizardSquareBtnActive: { backgroundColor: COLORS.tabBar, borderColor: COLORS.tabBar },
  wizardSquareText: { fontSize: 26, fontWeight: 'bold', color: COLORS.textPrimary },
  wizardGenderBtn: { backgroundColor: COLORS.card, width: '48%', padding: 20, borderRadius: 24, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  wizardGenderBtnActive: { backgroundColor: COLORS.tabBar, borderColor: COLORS.tabBar },
  wizardGenderText: { fontSize: 18, fontWeight: 'bold', color: COLORS.textPrimary, marginLeft: 10 },

  containerApp: { flex: 1, backgroundColor: COLORS.bg },
  contentArea: { flex: 1 },
  mainContent: { flexGrow: 1, padding: 20, paddingTop: Platform.OS === 'ios' ? 60 : TOP_INSET + 16, paddingBottom: 110 },
  centerView: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  placeholderText: { fontSize: 16, color: COLORS.textSecondary, textAlign: 'center', marginTop: 15, lineHeight: 24 },

  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 },
  greeting: { fontSize: 32, fontWeight: '900', color: COLORS.textPrimary, letterSpacing: -0.5 },
  subGreeting: { fontSize: 16, color: COLORS.tabBar, marginTop: 4, fontWeight: '700' },
  profileBtn: { padding: 5 },
  pageTitle: { fontSize: 32, fontWeight: '900', color: COLORS.textPrimary, letterSpacing: -0.5 },

  mainActionBtn: { backgroundColor: COLORS.tabBar, padding: 22, borderRadius: 24, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 20, shadowColor: COLORS.tabBar, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 6 },
  mainActionText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },

  metricCardFull: { width: '100%', backgroundColor: COLORS.card, padding: 24, borderRadius: 28, alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: COLORS.borderSoft, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.25, shadowRadius: 16, elevation: 4 },
  metricValueFull: { fontSize: 36, fontWeight: '900', color: COLORS.textPrimary, marginVertical: 8, letterSpacing: -1 },
  metricsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 },
  metricCard: { width: '48%', backgroundColor: COLORS.card, padding: 24, borderRadius: 28, alignItems: 'center', borderWidth: 1, borderColor: COLORS.borderSoft, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.22, shadowRadius: 14, elevation: 4 },
  metricTitle: { fontSize: 15, color: COLORS.textSecondary, fontWeight: '600' },
  metricValue: { fontSize: 26, fontWeight: '900', color: COLORS.textPrimary, marginVertical: 6, letterSpacing: -0.5 },
  miniBtn: { marginTop: 8, backgroundColor: 'rgba(34, 211, 238, 0.14)', paddingVertical: 8, paddingHorizontal: 16, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(34, 211, 238, 0.3)' },
  miniBtnText: { fontSize: 13, fontWeight: 'bold', color: COLORS.cyan },

  inputSection: { marginBottom: 30 },
  inputArea: { backgroundColor: COLORS.card, borderRadius: 20, padding: 20, fontSize: 16, height: 120, textAlignVertical: 'top', marginBottom: 15, color: COLORS.textPrimary, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },

  // --- Улучшенный трекер веса (Стиль Tracker) ---
  trackerCard: { backgroundColor: COLORS.card, borderRadius: 28, padding: 20, width: '100%', marginBottom: 20, borderWidth: 1, borderColor: COLORS.borderSoft, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.22, shadowRadius: 14, elevation: 4 },
  trackerTabs: { flexDirection: 'row' as const, backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 16, padding: 5, marginBottom: 24 },
  trackerTab: { flex: 1, paddingVertical: 10, alignItems: 'center' as const, borderRadius: 12 },
  trackerTabActive: { backgroundColor: 'rgba(139, 92, 246, 0.15)' },
  trackerTabText: { color: COLORS.textSecondary, fontSize: 14, fontWeight: '600' as const },
  trackerTabTextActive: { color: COLORS.tabBar, fontWeight: '800' as const },
  trackerPeriodLabel: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' as const, marginBottom: 4, textTransform: 'uppercase' as const, letterSpacing: 1 },
  trackerAvgValue: { color: COLORS.textPrimary, fontSize: 38, fontWeight: '900' as const, letterSpacing: -1 },
  trackerAvgSub: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '600' as const, marginTop: 4 },
  trackerDayView: { alignItems: 'center' as const, paddingVertical: 30 },
  trackerCurrentWeight: { color: COLORS.textPrimary, fontSize: 64, fontWeight: '900' as const, letterSpacing: -2 },
  trackerKgUnit: { color: COLORS.textSecondary, fontSize: 22, fontWeight: '600' as const, marginBottom: 12 },
  trackerDeltaBadge: { backgroundColor: 'rgba(255,255,255,0.03)', paddingHorizontal: 18, paddingVertical: 10, borderRadius: 24, marginTop: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  trackerDeltaText: { fontSize: 15, fontWeight: '800' as const },
  trackerDayTargetRow: { flexDirection: 'row' as const, alignItems: 'center' as const, marginTop: 20 },
  trackerDayTargetDash: { width: 20, height: 3, backgroundColor: COLORS.fat, borderRadius: 2, marginRight: 10 },
  trackerDayTargetText: { color: COLORS.fat, fontSize: 14, fontWeight: '700' as const },
  trackerStatsRow: { flexDirection: 'row' as const, borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.05)', paddingTop: 20, marginTop: 15 },
  trackerStat: { flex: 1, alignItems: 'center' as const },
  trackerStatLabel: { color: COLORS.textSecondary, fontSize: 10, fontWeight: '800' as const, letterSpacing: 1.2, marginBottom: 6 },
  trackerStatVal: { color: COLORS.textPrimary, fontSize: 20, fontWeight: '900' as const, letterSpacing: -0.5 },
  trackerTargetRow: { flexDirection: 'row' as const, alignItems: 'center' as const, marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  trackerTargetDash: { width: 24, height: 3, backgroundColor: COLORS.fat, borderRadius: 2, marginRight: 10 },
  trackerTargetNote: { color: COLORS.fat, fontSize: 14, fontWeight: '700' as const },
  trackerDaysNote: { color: 'rgba(255,255,255,0.2)', fontSize: 12, textAlign: 'center' as const, marginTop: 12, fontWeight: '500' },

  // --- Модальное окно веса ---
  wmOverlay: { flex: 1, backgroundColor: COLORS.bg },
  wmHeader: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const, paddingHorizontal: 25, paddingTop: Platform.OS === 'ios' ? 60 : TOP_INSET + 16, paddingBottom: 20 },
  wmTitle: { fontSize: 32, fontWeight: '900' as const, color: COLORS.textPrimary, letterSpacing: -0.5 },
  wmSubtitle: { fontSize: 14, color: COLORS.textSecondary, marginTop: 4, fontWeight: '600' as const },
  wmCloseBtn: { width: 44, height: 44, backgroundColor: COLORS.card, borderRadius: 22, alignItems: 'center' as const, justifyContent: 'center' as const, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  wmScroll: { flex: 1, paddingHorizontal: 20 },
  wmHero: { backgroundColor: COLORS.card, borderRadius: 28, padding: 25, marginBottom: 15, borderWidth: 1, borderColor: COLORS.borderSoft, alignItems: 'center' as const },
  wmHeroLabel: { fontSize: 11, color: COLORS.textSecondary, fontWeight: '800' as const, letterSpacing: 1.5 },
  wmHeroNum: { fontSize: 68, fontWeight: '900' as const, color: COLORS.textPrimary, letterSpacing: -2, lineHeight: 74 },
  wmHeroUnit: { fontSize: 24, fontWeight: '600' as const, color: COLORS.textSecondary, marginBottom: 10 },
  wmGoalRow: { flexDirection: 'row' as const, alignItems: 'center' as const, marginTop: 15 },
  wmGoalDash: { width: 20, height: 3, backgroundColor: COLORS.fat, borderRadius: 2, marginRight: 10 },
  wmGoalText: { fontSize: 14, color: COLORS.fat, fontWeight: '700' as const },
  wmProgressBg: { height: 6, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 4, overflow: 'hidden' as const },
  wmProgressFill: { height: '100%' as any, backgroundColor: COLORS.fat, borderRadius: 4 },
  wmProgressPct: { fontSize: 12, color: COLORS.textSecondary, textAlign: 'right' as const, marginTop: 6, fontWeight: '700' as const },
  wmInputCard: { backgroundColor: COLORS.card, borderRadius: 28, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: COLORS.borderSoft },
  wmInputLabel: { fontSize: 14, color: COLORS.textSecondary, fontWeight: '700' as const, marginBottom: 15, letterSpacing: 0.5, textAlign: 'center' },
  wmPickerRow: { flexDirection: 'row' as const, justifyContent: 'center' as const, alignItems: 'center' as const, marginBottom: 20 },
  wmPickerDot: { fontSize: 40, fontWeight: '900' as const, color: COLORS.tabBar, marginHorizontal: 5 },
  wmSaveBtn: { backgroundColor: COLORS.tabBar, padding: 18, borderRadius: 16, alignItems: 'center' as const },
  wmSaveBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' as const, letterSpacing: 0.5 },
  wmSectionTitle: { fontSize: 18, fontWeight: '800' as const, color: COLORS.textSecondary, marginBottom: 15, marginTop: 10, letterSpacing: 0.5, marginLeft: 5 },
  wmHistoryItem: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const, backgroundColor: COLORS.card, borderRadius: 20, padding: 20, marginBottom: 10, borderWidth: 1, borderColor: COLORS.borderSoft },
  wmHistoryDate: { fontSize: 16, color: COLORS.textPrimary, fontWeight: '700' as const },
  wmHistoryTime: { fontSize: 13, color: COLORS.textSecondary, marginTop: 4, fontWeight: '600' as const },
  wmHistoryWeight: { fontSize: 22, fontWeight: '900' as const, color: COLORS.textPrimary, letterSpacing: -0.5 },
  wmHistoryDelta: { fontSize: 14, fontWeight: '800' as const, marginTop: 4 },

  historyTitle: { fontSize: 22, fontWeight: '900', marginBottom: 20, color: COLORS.textPrimary, letterSpacing: -0.5 },
  historyCard: { backgroundColor: COLORS.card, padding: 20, borderRadius: 24, marginBottom: 15, borderWidth: 1, borderColor: COLORS.borderSoft },
  dateText: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  groupExerciseTitle: { fontSize: 20, fontWeight: '800', color: COLORS.textPrimary, marginBottom: 12, marginTop: 5 },
  exerciseSetText: { flex: 1, fontSize: 16, color: COLORS.textPrimary, fontWeight: '500' },
  setRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5, alignItems: 'center' },
  setDetails: { fontWeight: '800', color: COLORS.amber, fontSize: 16, marginTop: 2 },

  emptyGroupsContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 40 },
  emptyText: { fontSize: 20, fontWeight: '700', color: COLORS.textSecondary, marginVertical: 25, textAlign: 'center', paddingHorizontal: 30, lineHeight: 28 },
  centerActionBtn: { backgroundColor: COLORS.tabBar, width: '85%', padding: 22, borderRadius: 24, alignItems: 'center', elevation: 4 },
  actionButtonsRow: { width: '100%', alignItems: 'center' },
  groupsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingBottom: 50 },
  groupSquare: { width: '47%', height: 160, backgroundColor: COLORS.card, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: COLORS.borderSoft, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.22, shadowRadius: 14, elevation: 4 },
  groupSquareText: { marginTop: 15, fontSize: 18, fontWeight: '800', color: COLORS.textPrimary, paddingHorizontal: 10, textAlign: 'center' },

  groupDetailContainer: { flex: 1, backgroundColor: COLORS.bg },
  groupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 25, paddingTop: Platform.OS === 'ios' ? 60 : TOP_INSET + 16, backgroundColor: COLORS.card, borderBottomLeftRadius: 30, borderBottomRightRadius: 30, elevation: 5 },
  groupHeaderTitle: { flex: 1, fontSize: 26, fontWeight: '900', color: COLORS.textPrimary, textAlign: 'center', paddingHorizontal: 15, letterSpacing: -0.5 },
  memberCard: { backgroundColor: COLORS.card, padding: 20, borderRadius: 24, marginBottom: 15, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: COLORS.borderSoft },
  memberName: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary },
  memberRole: { fontSize: 13, color: COLORS.textSecondary, marginTop: 6, fontWeight: '600' },
  progressBarBg: { width: 90, height: 12, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 6, overflow: 'hidden', marginLeft: 15 },
  progressBarFill: { height: '100%', borderRadius: 6 },
  clientExerciseCard: { backgroundColor: 'rgba(255,255,255,0.03)', padding: 16, borderRadius: 20, marginBottom: 12, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },

  dateGroup: { marginBottom: 30 },
  dateHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, paddingHorizontal: 5 },
  dateHeaderText: { fontSize: 20, fontWeight: '800', color: COLORS.textPrimary, textTransform: 'capitalize' },
  sessionCard: { backgroundColor: COLORS.card, padding: 20, borderRadius: 24, marginBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: COLORS.borderSoft },
  sessionTimeBadge: { backgroundColor: 'rgba(139, 92, 246, 0.15)', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 12, marginRight: 15 },
  sessionTimeText: { color: COLORS.tabBar, fontWeight: '900', fontSize: 16 },
  sessionInfo: { flex: 1 },
  sessionDetailsTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary },
  emptyCardList: { padding: 30, borderRadius: 24, alignItems: 'center', marginTop: 30, backgroundColor: 'rgba(255,255,255,0.02)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  deleteBtn: { padding: 8, backgroundColor: 'rgba(239, 68, 68, 0.1)', borderRadius: 12 },

  modalOverlayFull: { flex: 1, backgroundColor: COLORS.bg, paddingTop: Platform.OS === 'ios' ? 60 : TOP_INSET + 16 },
  modalContentFull: { flex: 1, backgroundColor: COLORS.bg, borderTopLeftRadius: 35, borderTopRightRadius: 35, padding: 25 },
  modalHeaderFull: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderColor: 'rgba(255,255,255,0.05)', paddingBottom: 20, marginBottom: 15 },
  modalTitleFull: { fontSize: 26, fontWeight: '900', color: COLORS.textPrimary, letterSpacing: -0.5 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '90%', backgroundColor: COLORS.card, padding: 30, borderRadius: 32, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  modalTitle: { fontSize: 26, fontWeight: '900', marginBottom: 25, color: COLORS.textPrimary, letterSpacing: -0.5 },
  label: { fontSize: 16, fontWeight: '700', marginBottom: 12, alignSelf: 'flex-start', color: COLORS.textPrimary },
  selectItem: { width: '100%', backgroundColor: 'rgba(255,255,255,0.03)', padding: 20, borderRadius: 16, marginBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  selectItemText: { fontSize: 16, color: COLORS.textPrimary, fontWeight: '600' },
  pickerButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.03)', padding: 18, borderRadius: 16, marginBottom: 15, width: '100%', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  pickerButtonText: { marginLeft: 15, fontSize: 16, color: COLORS.textPrimary, fontWeight: '600' },

  sideMenuOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', flexDirection: 'row', justifyContent: 'flex-start' }, // Changed to slide from left
  sideMenuCloseArea: { flex: 1 },
  sideMenuContent: { width: '80%', maxWidth: 350, backgroundColor: COLORS.card, height: '100%', padding: 25, paddingTop: Platform.OS === 'ios' ? 70 : TOP_INSET + 26, borderTopRightRadius: 35, borderBottomRightRadius: 35 },
  sideMenuHeader: { alignItems: 'center', marginBottom: 30, paddingBottom: 30, borderBottomWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  sideMenuName: { fontSize: 24, fontWeight: '900', color: COLORS.textPrimary, marginTop: 15, textAlign: 'center', letterSpacing: -0.5 },
  sideMenuRole: { fontSize: 15, color: COLORS.textSecondary, marginTop: 6, fontWeight: '600' },
  sideMenuNav: { flex: 1 },
  sideMenuLink: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, marginBottom: 5, borderRadius: 16, paddingHorizontal: 10 },
  sideMenuLinkText: { fontSize: 18, color: COLORS.textPrimary, marginLeft: 20, fontWeight: '600' },
  sideMenuFooter: { borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.05)', paddingTop: 25, paddingBottom: 80, marginTop: 10 },
  sideMenuBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 10, borderRadius: 16 },
  sideMenuBtnText: { fontSize: 18, marginLeft: 20, fontWeight: '700', color: COLORS.textPrimary },

  settingsContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 25, marginTop: -50 },
  settingsTitle: { fontSize: 26, fontWeight: '900', color: COLORS.textPrimary, marginBottom: 15, letterSpacing: -0.5 },
  settingsDesc: { fontSize: 16, color: COLORS.textSecondary, textAlign: 'center', marginBottom: 50, paddingHorizontal: 20, lineHeight: 24 },
  dangerButton: { backgroundColor: 'rgba(239, 68, 68, 0.1)', padding: 22, borderRadius: 24, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', width: '100%', borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.3)' },
  dangerButtonText: { color: COLORS.error, fontSize: 18, fontWeight: 'bold' },

  accountSwitcherOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'flex-end' },
  accountSwitcherContent: { backgroundColor: COLORS.card, borderTopLeftRadius: 35, borderTopRightRadius: 35, padding: 25, paddingBottom: 50 },
  accountSwitcherHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 20, borderBottomWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  accountSwitcherTitle: { fontSize: 24, fontWeight: '900', color: COLORS.textPrimary, letterSpacing: -0.5 },
  accountItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 18, paddingHorizontal: 10, borderBottomWidth: 1, borderColor: COLORS.borderSoft },
  accountItemActive: { backgroundColor: 'rgba(139, 92, 246, 0.1)', borderRadius: 20, paddingHorizontal: 15, borderBottomWidth: 0, marginTop: 5, marginBottom: 5 },
  accName: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary },
  accEmail: { fontSize: 14, color: COLORS.textSecondary, marginTop: 4 },
  addAccountBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 25, justifyContent: 'center', marginTop: 10, backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 24 },
  addAccountText: { fontSize: 18, fontWeight: '800', marginLeft: 12, color: COLORS.textPrimary },

  tabBar: { flexDirection: 'row', backgroundColor: 'rgba(15, 19, 35, 0.96)', paddingHorizontal: 10, position: 'absolute', bottom: 0, width: '100%', justifyContent: 'space-around', alignItems: 'center', borderTopLeftRadius: 32, borderTopRightRadius: 32, borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.07)', shadowColor: '#000', shadowOffset: { width: 0, height: -6 }, shadowOpacity: 0.3, shadowRadius: 16, elevation: 12 },
  tabItem: { flex: 1, alignItems: 'center', paddingVertical: 10 },
  homeTabIcon: { width: 62, height: 62, borderRadius: 31, backgroundColor: COLORS.card, justifyContent: 'center', alignItems: 'center', marginTop: -26, borderWidth: 4, borderColor: COLORS.bg, overflow: 'hidden', shadowColor: COLORS.violet, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.5, shadowRadius: 12, elevation: 8 },

  chatContainer: { flex: 1, marginTop: 15 },
  chatBubble: { maxWidth: '85%', padding: 18, borderRadius: 24, marginBottom: 15 },
  chatBubbleUser: { backgroundColor: COLORS.indigo, alignSelf: 'flex-end', borderBottomRightRadius: 6 },
  chatBubbleAI: { backgroundColor: COLORS.card, alignSelf: 'flex-start', borderBottomLeftRadius: 6, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  chatText: { fontSize: 16, lineHeight: 24 },
  chatTextUser: { color: '#fff', fontWeight: '500' },
  chatTextAI: { color: COLORS.textPrimary },
  chatInputRow: { flexDirection: 'row', alignItems: 'flex-end', marginTop: 15, marginBottom: 10, paddingHorizontal: 5 },
  chatInput: { flex: 1, backgroundColor: COLORS.card, borderRadius: 24, padding: 18, paddingTop: 18, fontSize: 16, maxHeight: 120, color: COLORS.textPrimary, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  chatSendBtn: { backgroundColor: COLORS.tabBar, width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginLeft: 12, marginBottom: 0 },

  editMessageContainer: { backgroundColor: COLORS.card, padding: 18, borderRadius: 20, marginBottom: 15, borderWidth: 1, borderColor: COLORS.indigo, width: '90%', alignSelf: 'flex-end' },
  editMessageInput: { fontSize: 16, color: COLORS.textPrimary, borderBottomWidth: 1, borderColor: 'rgba(255,255,255,0.1)', paddingBottom: 10, marginBottom: 15, minHeight: 40 },
  editMessageActions: { flexDirection: 'row', justifyContent: 'flex-end' },
  editIconBtn: { position: 'absolute', bottom: -12, left: -12, backgroundColor: COLORS.card, borderRadius: 16, width: 32, height: 32, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },

  chatSidebarOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', flexDirection: 'row' },
  chatSidebarContent: { width: '80%', maxWidth: 350, backgroundColor: COLORS.card, height: '100%', padding: 25, paddingTop: Platform.OS === 'ios' ? 60 : TOP_INSET + 16, borderTopRightRadius: 35, borderBottomRightRadius: 35 },
  chatSidebarCloseArea: { flex: 1 },
  newChatBtnSidebar: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.tabBar, padding: 18, borderRadius: 20, marginBottom: 35, justifyContent: 'center' },
  newChatBtnTextSidebar: { color: '#fff', fontSize: 18, fontWeight: '800', marginLeft: 12 },
  sidebarSectionTitle: { fontSize: 14, color: COLORS.textSecondary, marginBottom: 20, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  chatSidebarItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, paddingHorizontal: 16, borderRadius: 16, marginBottom: 8 },
  chatSidebarItemActive: { backgroundColor: 'rgba(255,255,255,0.05)' },
  chatSidebarItemText: { fontSize: 16, color: COLORS.textPrimary, flex: 1, fontWeight: '600' },

  macrosRowContainer: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: 15 },
  macroCard: { backgroundColor: COLORS.card, width: '31%', padding: 18, borderRadius: 24, alignItems: 'center', borderWidth: 1, borderColor: COLORS.borderSoft, shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.2, shadowRadius: 10, elevation: 3 },
  macroLabel: { fontSize: 15, color: COLORS.textSecondary, fontWeight: '800', marginBottom: 8 },
  macroValueSmall: { fontSize: 15, color: COLORS.textPrimary, marginBottom: 12, fontWeight: '800' },
  macroProgressBg: { width: '100%', height: 8, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 4, overflow: 'hidden' },
  macroProgressFill: { height: '100%', borderRadius: 4 },

  previewContainer: { backgroundColor: 'rgba(255,255,255,0.02)', padding: 25, borderRadius: 24, marginTop: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  previewTitle: { fontSize: 20, fontWeight: '900', color: COLORS.textPrimary, textAlign: 'center', marginBottom: 8, letterSpacing: -0.5 },
  previewCals: { fontSize: 28, fontWeight: '900', color: COLORS.emerald, textAlign: 'center', marginBottom: 20, letterSpacing: -1 },
  previewMacrosRow: { flexDirection: 'row', justifyContent: 'space-around', borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.05)', paddingTop: 20 },
  previewMacro: { alignItems: 'center' },
});
